#include <iostream>

int Main();

int main()
{
    try {
        Main();
    }
    catch(Koala::Error::AlgExcWrongConn &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::AlgExcWrongMask &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::AlgExcNullEdge &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::AlgExcNullVert &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::AlgExcWrongArg &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::AlgExc &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExcWrongMask &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExcNullEdge &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExcNullVert &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExcWrongConn &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExcWrongArg &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::GraphExc &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ContExcPoolNotEmpty &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ContExcFull &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ContExcOutpass &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ContExcWrongArg &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ContExc &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcWrongMask &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcWrongConn &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcNullEdge &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcNullVert &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcWrongArg &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
    catch(Koala::Error::ExcBase &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}

//    catch(Koala::Error::ContExcEmpty &ex) { std::cerr << "\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nBlad!!!\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nTyp: " << ex.type() <<"\nPlik: " <<ex.file() <<"\nWiersz: "<< ex.line() <<"\nZlamano warunek: "<<ex.descr() <<"\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";}
}

int Main(){
